# Common definitions for building SailfishOS on Sony devices

# Fix signapk build error
PRODUCT_PACKAGES += \
	conscrypt-host \
	libconscrypt_openjdk_jni

# Generated by:
# ./external/audioflingerglue/detect_build_targets.sh $PORT_ARCH $(gettargetarch)
# Where gettargetarch returns "arm"
PRODUCT_PACKAGES += \
	libaudioflingerglue \
	miniafservice

# Generated by:
# ./external/droidmedia/detect_build_targets.sh $PORT_ARCH $(gettargetarch)
# Where gettargetarch returns "arm"
PRODUCT_PACKAGES += \
	libdroidmedia \
	minimediaservice \
	minisfservice \
	libminisf
